format = """
$os$shell [$directory](bold cyan)($git_branch$git_state$git_status$git_metrics) ($c$conda$python)
$time $username ($battery) $character"""

[character]
disabled = false
success_symbol = '[»](bold green)'
error_symbol = '[»](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'

[shell]
format = '[❮](bold yellow)[$indicator]($style)[❯](bold yellow)'
powershell_indicator = 'pwsh'
fish_indicator = 'fish'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[sudo]
style = 'bold green'
symbol = ' ‍  '
disabled = false

[git_branch]
style = "bold green"
format = "[\\[[$symbol$branch$tag](bold green)\\]](bold white)"
symbol = "\ue725 "

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[conda]
disabled = false
ignore_base = false
symbol = "󰬊 "
format = 'via [$symbol]($style)[$environment](blue bold)'

[python]
disabled = false
pyenv_version_name = false
symbol = " "
style = "blue bold" 

[hostname]
ssh_only = true
format = "[$hostname]($style)"
style = "bold white"

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"

[os]
format = '[$symbol]($style)'
style = 'bold blue'
disabled = false

[os.symbols]
Ubuntu = "󰕈 "
Windows = " "
Raspbian = " "
Kali = " "
Macos = " "

[battery]
disabled = false
format = '[$symbol$percentage]($style)'
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
empty_symbol = '󰁺 '

[[battery.display]]
threshold = 100
style = 'bold green'

[[battery.display]]
threshold = 60
style = 'bold yellow'

[[battery.display]]
threshold = 20
style = 'bold red'